### ISSUE TITLE
How to override endpoint(http://localhost:9411/api/v1/spans) property of classzipkin.reporter.urlconnectio.URLConnectionSender of 

### ISSUE THREAD

**Issue by shuchitaprasad** [openzipkin/zipkin-js#102]
I have a cloud slueth zipkin application A1 in spring boot. I also have a zipkin server application A2 in spring boot.When I run the zipkin server A2 at localhost at default port 9411, then A1 trace ids are sent to zipkin server A2. When the port of the zipkin server is changed and is successfully started at the new port 9455, the application A1 fails to send logs to zipkin-server. URLConnectionSender{encoding=THRIFT, messageMaxBytes=5242880, encoder=THRIFT, endpoint=http://localhost:9411/api/v1/spans, connectTimeout=10000, readTimeout=60000, compressionEnabled=false, mediaType=application/x-thrift})] WARN  z.r.AsyncReporter$BoundedAsyncReporter - Dropped 1 spans due to ConnectException(Connection refused: connect). The cloud slueth zipkin server end point is not changing even when following properties are set in aplication.yml
spring.zipkin.baseUrl = corrrect host and port and 

sample:
  zipkin:
    enabled: true

**Comment by Odravison** [comment]
Hey Man, I know that is a old post, but if you can help me ...
I'm getting this erro: 
```
2017-05-23 01:48:47.896  WARN [ping-service,,,] 23993 --- [ender@370f3e50)] z.r.AsyncReporter$BoundedAsyncReporter   : Dropped 3 spans due to ResourceAccessException(I/O error on POST request for "http://localhost:9411/api/v1/spans": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused))

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v1/spans": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.post(RestTemplateSender.java:73) ~[spring-cloud-sleuth-zipkin-1.2.0.RELEASE.jar!/:1.2.0.RELEASE]
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.sendSpans(RestTemplateSender.java:46) ~[spring-cloud-sleuth-zipkin-1.2.0.RELEASE.jar!/:1.2.0.RELEASE]
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228) [zipkin-reporter-0.6.12.jar!/:na]
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153) [zipkin-reporter-0.6.12.jar!/:na]
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source) [zipkin-reporter-0.6.12.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_131]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[na:1.8.0_131]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 8 common frames omitted
```
This Microservice is running at AWS. I think that is firewall's issue.

**Comment by pdqsoftware-datax** [comment]
Hi Odravison,
Did you resolve your issue above?
I am getting exactly the same thing now on a local server - where everything lives - so I am pretty sure it is not a firewall issue.
Any pointers would be useful.
Thanks
Paul

**Comment by adriancole** [comment]
you are posting issues about spring-cloud-sleuth on zipkin-js (javascript repository). There is no code related to the issue you are mentioning here. Please post on appropriate forums. For general troubleshooting of spring-cloud-sleuth https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by pratsonii** [comment]
Hi Odravison,
I am facing same issue. Did find the work around?

**Comment by Odravison** [comment]
Hi, @pratsonii 
This issues has relation with endpoint.
As I told to Paul Pritchard, has sometime that I solve this issue and forgot the solution. But I remember that has a relation with endpoint, in my case, was the Zuul Proxy that I had configured was the cause of my problem. Are you using Zuul Proxy?

In resume, take a look to your endpoint.

[]'s

**Comment by adriancole** [comment]
This is not a java repository, it is a javascript repository. It seems from discussion you are using spring-cloud-sleuth. Please carry any troubleshooting conversation on their gitter or stackoverflow https://gitter.im/spring-cloud/spring-cloud-sleuth


I'm locking comments as they continue to spam an unrelated project
