### ISSUE TITLE
TypeError: Cannot read property 'JSON_V1' of undefined

### ISSUE THREAD

**Issue by DanielMSchmidt** [openzipkin/zipkin-js#145]
I get this when importing the HTTPLogger:

```sh
TypeError: Cannot read property 'JSON_V1' of undefined

    at Object.<anonymous> (node_modules/zipkin-transport-http/lib/HttpLogger.js:14:36)
    at Object.<anonymous> (node_modules/zipkin-transport-http/lib/index.js:3:29)
    at Object.<anonymous> (src/index.js:13:1)
```

**Comment by pbadenski** [comment]
What are the zipkin* packages versions?

**Comment by DanielMSchmidt** [comment]
I found my issue, I configured my mock incorrectly

Pawel Badenski <notifications@github.com> schrieb am Mi., 1. Nov. 2017,
18:09:

**Comment by DanielMSchmidt** [comment]
Found my issue, I configured the mock incorrectly
