### ISSUE TITLE
require.call workaround causes warnings in webpack

### ISSUE THREAD

**Issue by AvivRubys** [openzipkin/zipkin-js#155]
In `zipkin` and `zipkin-transport-http` you use `require.call(null, 'package')` to avoid some bundlers (which?) from detecting it as a missing dependency.
However, when used under webpack, it spits out warnings about using `require` dynamically in `InetAddress.js` and `HttpLogger.js`
The exact warning is `23:27-34 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`
I couldn't find any way to silence the output for only two specific files, unfortunately.
Is there something we can do on the library side to alleviate this?

**Comment by hollinwilkins** [comment]
This will cause a runtime error later when trying to use the HttpLogger:

```
Error: Cannot find module "."
    at webpackMissingModule (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/node_modules/zipkin-transport-http/lib/HttpLogger.js:11:1)
    at Object.webpackEmptyContext.keys (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/node_modules/zipkin-transport-http/lib/HttpLogger.js:11:1)
    at __webpack_require__ (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/webpack/bootstrap 57858a24cec3e7a41b44:19:1)
    at Object.<anonymous> (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/node_modules/zipkin-transport-http/lib/index.js:3:1)
    at __webpack_require__ (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/webpack/bootstrap 57858a24cec3e7a41b44:19:1)
    at Object.webpackEmptyContext.keys (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/src/server/createTracer.js:2:1)
    at __webpack_require__ (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/webpack/bootstrap 57858a24cec3e7a41b44:19:1)
    at Object.<anonymous> (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/src/server/server.js:16:1)
    at __webpack_require__ (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/webpack/bootstrap 57858a24cec3e7a41b44:19:1)
    at Object.defineProperty.value (/Users/hollinwilkins/go/src/propel.ai/aai-platform/web-ui/packages/buyer-ui/build/server/webpack:/src/server/index.js:2:1)
```

Not sure how to get around this aside from not using webpack. I think this could help: https://webpack.js.org/plugins/context-replacement-plugin/

But I'm not familiar enough with how it works to come up with a solution.

**Comment by hollinwilkins** [comment]
Found a workaround for the error I was getting. Needed to make a wrapper JS file that does this:

```
// Needed to run Zipkin in production after webpacking
global.fetch = require('node-fetch')

require('./bootstrap')
```

**Comment by pathikmehta** [comment]
**This workorund worked for my react application to resolve this issue in IE**

I have tried to resolve this error by changing `require.call()` to `require()`.
This does remove the warning from console while starting the server. But then it started giving this error at runtime.
`SCRIPT5007: Unable to get property 'bind' of undefined or null reference`

Looks like this error occurs because `node-fetch` expects `window.fetch` object available based on [this](https://github.com/bitinn/node-fetch/blob/d522036bee580abdca0fc6ab7afcd38f573e4f96/browser.js#L4) line of code in `node-fetch`.

This issue is specific to Internet Explorer becuase default `fetch` implementation is not available in `window.fetch` object in Internet Explorer which is there in other browser like chrome.

To resolve this issue, We need to make an `fetch` implementation available in `window.fetch` object for Internet Explorer browser.

To do that I need to add `whatwg-fetch` in my application. After adding `whatwg-fetch` I have imported `whatwg-fetch` in index file of my application.
```javascript
import 'whatwg-fetch';
```

As my application code is executing on browser (client side) I have used `whatwg-fetch`. If your application code is executing on `node` environment then you should use `node-fetch` or `cross-fetch` or any similar implementation of `fetch` available for `node` environment.

Note:- To resolve this error first `require.call()` from zipkin source code need to be changed to `require()`
