### ISSUE TITLE
Support for old node versions

### ISSUE THREAD

**Issue by sahas-** [openzipkin/zipkin-js#167]
Hi,
I want to instrument express.js service, this service will be hosted on a platform that supports upto **node v0.10.43**. In that environment, I'm getting below error 

Is this expected? 
I know this is one off case, wondering if anyone solved this problem.

`dist/node_modules/zipkin-transport-http/lib/HttpLogger.js:34
    this.headers = Object.assign({
                          ^

TypeError: Object function Object() { [native code] } has no method 'assign'
    at new HttpLogger (dist/node_modules/zipkin-transport-http/lib/HttpLogger.js:34:27)
    at Object.<anonymous> (dist/recorder.js:13:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (dist/server.js:14:17)
    at Module._compile (module.js:456:26)`

**Comment by sahas-** [comment]
Just an update, I had to use a few babel plugins "babel-plugin-transform-object-assign", "babel-polyfill" to get this working on this environment.

**Comment by eirslett** [comment]
That's right - zipkin-js is only officially supported on node 4+ (for the current version). For version 1.0 onwards, only node 8+ will be supported.
