### ISSUE TITLE
BatchRecorder throws error: "TypeError: Cannot read property 'delegate' of undefined"

### ISSUE THREAD

**Issue by spoulson** [openzipkin/zipkin-js#169]
Reproduce:

1. Start a span with ServerRecv
1. Do something that takes longer than the span timeout (default 1 minute).  Span is now expired and deleted.
1. Terminate the span with ServerSend.

Get error:
```
TypeError: Cannot read property 'delegate' of undefined
      at BatchRecorder._writeSpan (src/batch-recorder.js:51:29)
      at BatchRecorder._updateSpanMap (src/batch-recorder.js:69:12)
      at BatchRecorder.record (src/batch-recorder.js:82:10)
      at id.sampled.ifPresent.sampled (src/tracer/index.js:161:21)
      at Some.map (src/option.js:36:21)
      at Some.ifPresent (src/option.js:39:17)
      at Tracer.recordAnnotation (src/tracer/index.js:158:21)
      at ctxImpl.scoped (test/batch-recorder.test.js:207:13)
      at ExplicitContext.scoped (src/explicit-context.js:16:20)
      at Context.it (test/batch-recorder.test.js:202:13)
```

**Comment by spoulson** [comment]
https://github.com/openzipkin/zipkin-js/pull/168

**Comment by spoulson** [comment]
Merged.
