### ISSUE TITLE
Error: Cannot find module 'zipkin-instrumentation-grpc-client'

### ISSUE THREAD

**Issue by li8** [openzipkin/zipkin-js#323]
I have included zipkin-instrumentation-grpc-client using npm install 

`npm install zipkin-instrumentation-grpc-client@0.15.0 --save`

On running the application, I get the error 
`Error: Cannot find module 'zipkin-instrumentation-grpc-client'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/300027553/Work/wit/mwpserver/server/grpc/client/workouts.js:5:1)
    at Module._compile (module.js:652:30)
    at loader (/Users/300027553/Work/wit/mwpserver/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/300027553/Work/wit/mwpserver/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)`

This is because in package.json, the main file points to `lib/grpcClient.js`.

But there is no such file.

**Comment by jcchavezs** [comment]
Thanks @li8, I am pinging @ghermeto as he is the original author of this package.

**Comment by li8** [comment]
For now , I use the postInstall script in package.json 
`postinstall: mv node_modules/zipkin-instrumentation-grpc-client/lib/grpcClientInterceptor.js node_modules/zipkin-instrumentation-grpc-client/lib/grpcClient.js`

**Comment by jcchavezs** [comment]
closed by #324
